# Generated by Django 3.2.25 on 2026-02-19 06:07

from django.db import migrations, models
import settings.models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=settings.models.feedback_upload_path),
        ),
    ]
